In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression,Ridge,Lasso

In [2]:
df = pd.read_csv("./cardekho_dataset.csv/cardekho_dataset.csv")

In [3]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [5]:
obj_cols = df.select_dtypes("object").columns

In [6]:
df = pd.get_dummies(df, columns=obj_cols, drop_first=True)

In [7]:
df.head()

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,car_name_Audi A6,car_name_Audi A8,...,model_i10,model_i20,model_redi-GO,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,0,9,120000,19.70,796,46.30,5,120000,False,False,...,False,False,False,True,False,False,False,False,True,True
1,1,5,20000,18.90,1197,82.00,5,550000,False,False,...,False,False,False,True,False,False,False,False,True,True
2,2,11,60000,17.00,1197,80.00,5,215000,False,False,...,False,True,False,True,False,False,False,False,True,True
3,3,9,37000,20.92,998,67.10,5,226000,False,False,...,False,False,False,True,False,False,False,False,True,True
4,4,6,30000,22.77,1498,98.59,5,570000,False,False,...,False,False,False,False,False,True,False,False,False,True

In [8]:
df = df.drop("Unnamed: 0", axis=1)

In [9]:
df.head()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,car_name_Audi A6,car_name_Audi A8,car_name_Audi Q7,...,model_i10,model_i20,model_redi-GO,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,fuel_type_Petrol,transmission_type_Manual
0,9,120000,19.70,796,46.30,5,120000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
1,5,20000,18.90,1197,82.00,5,550000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
2,11,60000,17.00,1197,80.00,5,215000,False,False,False,...,False,True,False,True,False,False,False,False,True,True
3,9,37000,20.92,998,67.10,5,226000,False,False,False,...,False,False,False,True,False,False,False,False,True,True
4,6,30000,22.77,1498,98.59,5,570000,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop("selling_price", axis=1)
y = df["selling_price"]

X_train, X_test , y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
slr = LinearRegression()
slr.fit(X_train, y_train)

LinearRegression()

In [13]:
y_pred = slr.predict(X_test)
y_pred_train = slr.predict(X_train)

In [14]:
from sklearn.metrics import r2_score , mean_absolute_error, mean_squared_error

print("r^2 :- ",r2_score(y_test, y_pred))
print("mean_absolute_error :- ", mean_absolute_error(y_test, y_pred))
print("mean_squared_error :- ", mean_squared_error(y_test, y_pred))
print()
print("Training Data error :- ")
print()
print("r^2 :- ",r2_score(y_train, y_pred_train))
print("mean_absolute_error :- ", mean_absolute_error(y_train, y_pred_train))
print("mean_squared_error :- ", mean_squared_error(y_train, y_pred_train))

r^2 :-  0.789573404016972
mean_absolute_error :-  179739.40527177879
mean_squared_error :-  158405309689.39066

Training Data error :-

r^2 :-  0.8534962701261495
mean_absolute_error :-  167198.2974840638
mean_squared_error :-  118819621204.42546

In [15]:
from sklearn.linear_model import RidgeCV

alphas = [0.001, 0.01, 0.1, 1, 5, 10, 20, 50, 100]

ridge_cv = RidgeCV(alphas=alphas, cv=5)
ridge_cv.fit(X_train, y_train)

print("Best Alpha:", ridge_cv.alpha_)

Best Alpha: 100.0

In [16]:
ridge = Ridge(alpha=ridge_cv.alpha_)
ridge.fit(X_train, y_train)

Ridge(alpha=np.float64(100.0))

In [17]:
y_pred = ridge.predict(X_test)
y_pred_train = ridge.predict(X_train)

In [18]:
print("r^2 :- ",r2_score(y_test, y_pred))
print("mean_absolute_error :- ", mean_absolute_error(y_test, y_pred))
print("mean_squared_error :- ", mean_squared_error(y_test, y_pred))
print()
print("Training Data error :- ")
print()
print("r^2 :- ",r2_score(y_train, y_pred_train))
print("mean_absolute_error :- ", mean_absolute_error(y_train, y_pred_train))
print("mean_squared_error :- ", mean_squared_error(y_train, y_pred_train))

r^2 :-  0.7889624833576915
mean_absolute_error :-  179076.9273012112
mean_squared_error :-  158865199637.12698

Training Data error :-

r^2 :-  0.8533811645837589
mean_absolute_error :-  166358.30724496476
mean_squared_error :-  118912975803.36403

In [22]:
from sklearn.linear_model import LassoCV

alphas = [0.001, 0.01, 0.1, 1, 5, 10, 20, 50, 100]

lcv = LassoCV(
    alphas=alphas,
    cv=5,
    max_iter=10000,
    random_state=42
)

lcv.fit(X_train, y_train)
print("best lasso ap", lcv.alpha_)

best lasso ap 100.0

In [26]:
nor_lcv = Lasso(alpha=lcv.alpha_, max_iter=10000)
nor_lcv.fit(X_train, y_train)

Lasso(alpha=np.float64(100.0), max_iter=10000)

In [27]:
y_pred = nor_lcv.predict(X_test)
y_pred_train = nor_lcv.predict(X_train)

In [28]:
print("r^2 :- ",r2_score(y_test, y_pred))
print("mean_absolute_error :- ", mean_absolute_error(y_test, y_pred))
print("mean_squared_error :- ", mean_squared_error(y_test, y_pred))
print()
print("Training Data error :- ")
print()
print("r^2 :- ",r2_score(y_train, y_pred_train))
print("mean_absolute_error :- ", mean_absolute_error(y_train, y_pred_train))
print("mean_squared_error :- ", mean_squared_error(y_train, y_pred_train))

r^2 :-  0.7948382939245137
mean_absolute_error :-  178723.9685915217
mean_squared_error :-  154441996438.09448

Training Data error :-

r^2 :-  0.8534853000404987
mean_absolute_error :-  167078.31569123524
mean_squared_error :-  118828518325.49342